spring:
  application.name: bot-platform
  profiles.active: ${IGOR_BOT_ACTIVE_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/common
bot:
  name: ${IGOR_BOT_USERNAME}
  token: ${IGOR_BOT_TOKEN}
  baseUrl: ${BASE_URL}
  supportChat: ${IGOR_BOT_SUPPORT_CHAT:-1001063148517}
http:
  proxy:
    url: ${PROXY_URL:}
---
spring:
  profiles: say-text
polly:
  access-key: ${POLLY_ACCESS_KEY}
  secret-key: ${POLLY_SECRET_KEY}
file-service:
  url: ${FILE_SERVICE_URL}
---
spring:
  profiles: dev
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.web: DEBUG
    ru.javazen.telegram.bot: DEBUG
    org.hibernate: DEBUG
---
spring:
  profiles: production
  datasource:
    url: ${IGOR_DB_CONNECTION_URL}
    username: ${IGOR_DB_USER}
    password: ${IGOR_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration/common,db/migration/postgresql
logging:
  level:
    org.springframework.web: INFO
    ru.javazen.telegram.bot: INFO
    org.hibernate: INFO